version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: admin       # Логин для суперпользователя
        POSTGRES_PASSWORD: secret  # Пароль (замените на свой)
        POSTGRES_DB: cafe         # Название БД (опционально)
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge